version: '3.8'

services:
  ganache:
    # This 'build' section tells Docker to build an image from your local files
    build:
      context: .
      dockerfile: Dockerfile.ganache
    # We give it a unique name to make it yours
    container_name: my-ganache-blockchain
    ports:
      - "8545:8545"
    volumes:
      - blockchain_data:/app

  streamlit-app:
    # This 'build' section builds the Streamlit app from your local files
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    # A unique name for your app container
    container_name: my-certificate-app
    ports:
      # You can change the first number to any port you like (e.g., "8502:8501")
      - "8501:8501"
    depends_on:
      - ganache
    volumes:
      - blockchain_data:/app

volumes:
  blockchain_data: